# .scrutinizer.yml
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
build:
    environment:
            php: '5.5.12'
    tests:
        override:
            -
                command: phpunit --coverage-clover=coverage.clover
                coverage:
                    file: coverage.clover
                    format: php-clover
checks:
    php:
        code_rating: true
        duplication: true